name: placear.com
favicon: null
layout_spectrum: 0.7793195224367082
typography_spectrum: 0.31013
title: Placear
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6a8b7'
    - '#33da9a'
    - '#399deb'
    - '#2d313a'
    - '#fefeff'
  brandStrength: 0.6453232383355498
  lightness: 0.8761882453691214
  saturation: 0.5243659422267228
  rhythmicContrast: 0.7471721770707518
purpose: []
